# Generated by Django 3.2.9 on 2021-11-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Crypto', 'crypto'), ('Stocks', 'stocks')], max_length=50)),
                ('idea', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=6)),
                ('risk', models.CharField(max_length=15)),
                ('target', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('like', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
    ]
